development:
  adapter: sqlite3
  database: db/development.sqlite3.db

test:
  adapter: sqlite3
  database: db/test.sqlite3.db

production:
  adapter: postgresql
  encoding: utf8
  database: rails_production
  username: rails
