development:
  adapter: postgresql
  database: wittbib_development
  encoding: UTF8
  username: 
  password: 
  host: localhost
  template: template0


test:
  adapter: postgresql
  database: wittbib_test
  encoding: UTF8
  username: 
  password: 
  host: localhost
  template: template0

production:
  adapter: postgresql
  database: wittbib_production
  encoding: UTF8
  username:
  password: 
  host: localhost
  template: template0

